accountsDesc = {
    "finedeco@rogers.com": "Fine Decor International Inc.",
    "StuartStorm@gotchacovered.com": "Gotcha Covered (Storm Design Inc)",
    "Gotchacoveredtorontocentral@gmail.com": "Gotcha Covered (Storm Design Inc)",
    "Lindsay@patti-lynn.com": "Patti Lynn Int.",
    "john@mapledrapery.com": "Maple Drapery and Carpet (1988 Ltd.)",
    "joannabaker81@gmail.com": "Window Wraps / Blinds Depot",
    "william@eurofab.ca": "Eurofab Inc.",
    "kellie@drapeology.com": "Drapeology Inc.",
    "sebastien@mysunglow.com": "Sun Glow Window Covering Products of Canada Ltd.",
    "Al@200Vic.com": "200 Vic Ltd.",
    "admin@2codesign.ca": "2Co.Design Build Inc.",
    "kenluu618@yahoo.com": "3 Coms Shutters Window Fashion",
    "amit@coloursandmore.com": "AM 10011152 - Colours and More Enterprises Inc",
    "thomsens@rogers.com": "AM 1042781 - Thomsen's Decorating Centre",
    "mikem@paintdepot.com": "AM 116458 - Paint Depot O'Connor",
    "artisticinteriors@hotmail.com": "AM 398775 - Artistic Interiors",
    "karen@ashtonsblinds.com": "Ashton's Blinds Draperies Shutters",
    "Info@auropol.ca": "Auropol Creative Window Decor",
    "sherree@avenuelighting.ca": "Avenue Lighting & Design Inc. 597602",
    "avenueofstyles@gmail.com": "Avenue of Styles",
    "stefanie@blindsareus.ca": "Blinds Are Us",
    "Showroom@blindsareus.ca": "Blinds Are Us",

    "blindspot@fibreop.ca": "Blindspot",
    "beverley@cocooninteriors.ca": "Cocoon Interiors Inc.",
    "yolanda@colouroasis.ca": "Colour Oasis Paint & Decor Limited",
    "petra@cvshading.com": "Commercial Vision",
    "anita@cvshading.com": "Commercial Vision",

    "dani@gambitventures.ca": "Condo Blinds (Gambit Ventures Ltd.)",
    "coverups@outlook.com": "Cover Ups",
    "lilyandvince@dekoblinds.ca": "DekoBlinds",
    "james@devineblinds.net": "Devine Blinds & Drapery",
    "charlenebertini@gmail.com": "Charlene Bertini",
    "don@drapeology.com": "Drapeology Inc.",
    "maria@drapesandmore.ca": "Drapes & More",
    "barbara@evershades.ca": "EverShades (Lotus Window Coverings Inc.)",
    "info@faabhomefashions.com": "faAB HomeFashions Ltd.",
    "lbildfell@flooringandhome.com": "Flooring and Home (9170634 Canada Inc)",
    "georgiaprendergast@gotchacovered.com": "Gotcha Covered - N. Kitchener- & Waterloo",
    "peterbuchsbaum@gotchacovered.com": "Gotcha Covered (New View Designs)",
    "clairwoodland@gotchacovered.com": "Gotcha Covered Barrie (2574448 Ontario Inc.)",
    "croteau@gotchacovered.com": "Gotcha Covered Brampton (2481658 ON Inc)",
    "mikecyr@gotchacovered.com": "Gotcha Covered Durham East (2570287 ON Inc.)",
    "bakers@gotchacovered.com": "Gotcha Covered Escarpment",
    "carolannhorvat@gotchacovered.com": "Gotcha Covered Richmond Hill",
    "insideideas@bellnet.ca": "Inside Ideas",
    "Jalynwirth@gmail.com": "Ja Lyn Services & Decor",
    "kathryn@kathrynastoninteriors.com": "Kathryn Aston Interiors",
    "kazumicovering@gmail.com": "Kazumi Window Coverings (Samyak Inc.)",
    "kevin@kendallandco.ca": "Kendall & Co Interior Design & Decor",
    "design@kingstonpaint.com": "Kingston Paint & Decorating Inc.",
    "harvey@lrnerinteriors.com": "Lerner Interiors",
    "info@lincolndesignhouse.ca": "Lincoln Design House",
    "purchasing@mnidonline.com": "Mike Niven Interior Design Inc",
    "rethier@gmail.com": "North Bay Blinds",
    "lindsay@patti-lynn.com": "Patti Lynn Int.",
    "tscustomdrapery@hotmail.com": "Picture Perfect Window Coverings",
    "info@promarkwindowfilm.com": "Promark Window Film & Blinds",
    "1dilu1@gmail.com": "R.C. Services (BetterDealBlinds.ca)",
    "amanda@rbfurnitureshop.com": "Red Bean Interior Design Inc.",
    "rmcavoy_design@yahoo.ca": "Rhonda McAvoy",
    "douglaswentzel@bellnet.ca": "Rise 'N' Shine",
    "rosewell.interiors@gmail.com": "Rosewell Custom Interiors",
    "dan@shuttercraft.ca": "Shutter Craft Window Coverings",
    "bren@swi.design": "Simply White Interiors",
    "annfitch@stevansinc.com": "Stevans Sales",
    "doug@condokandy.com": "Suite Shades by KANDY (KANDY Operations Inc.)",
    "sunsetblinds@hurontel.on.ca": "Sunset Blinds Ltd.",
    "taipan2004@rogers.com": "Tai Pan Blinds & Drapes",
    "karen_gordon@rogers.com": "The Blind People",
    "blinds@thedecoratingcentre.ca": "The Decorating Centre",
    "wardsdraperies@rogers.com": "Ward's Draperies",
    "John@OntarioWallBeds.com": "London Window Treatment Inc.",
    "kelly@coloursandmore.com": "AM 10011152 - Colours and More Enterprises Inc",
    "alanna@paintdepot.com": "AM 116458 - Paint Depot O'Connor",
    "larissa@avenuelighting.ca": "Avenue Lighting & Design Inc. 597602",
    "ashley@thebauhaus.ca": "Blinds Are Us",
    "chris@colouroasis.ca": "Colour Oasis Paint & Decor Limited",
    "sales@cvshading.com": "Commercial Vision",
    "jordan@condoblinds.com": "Condo Blinds (Gambit Ventures Ltd.)",
    "admin@drapesandmore.ca": "Drapes & More",
    "psierra@flooringandhome.com": "Flooring and Home (9170634 Canada Inc)",
    "jjwirth@telus.net": "Ja Lyn Services & Decor",
    "kendall@kendallandco.ca": "Kendall & Co Interior Design & Decor",
    "lukas@mapledrapery.com": "Maple Drapery and Carpet (1988 Ltd.)",
    "nbblinds.sally@gmail.com": "North Bay Blinds",
    "PATTI-LYNN@PATTI-LYNN.COM": "Patti Lynn Int.",
    "judy.pictureperfect@gmail.com": "Picture Perfect Window Coverings",
    "bschaefer@promarkwindowfilm.com": "Promark Window Film & Blinds",
    "kristilee@rbfurnitureshop.com": "Red Bean Interior Design Inc.",
    "westwoodwindowfashions@sympatico.ca": "Westwood WIndow Fashion",
    "jennifer@swi.design": "Simply White Interiors",
    "becky@stevansinc.com": "Stevans Sales",
    "kelly@condokandy.com": "Suite Shades by KANDY (KANDY Operations Inc.)",
    "yvonnebc1@rogers.com": "Tai Pan Blinds & Drapes",
    "drapery@thedecoratingcentre.ca": "The Decorating Centre",
    "Amy@OntarioWallBeds.com": "London Window Treatment Inc.",
    "info@coloursandmore.com": "AM 10011152 - Colours and More Enterprises Inc",
    "sarah@paintdepot.com": "AM 116458 - Paint Depot O'Connor",
    "kayla@avenuelighting.ca": "Avenue Lighting & Design Inc. 597602",
    "jody@colouroasis.ca": "Colour Oasis Paint & Decor Limited",
    "will@kendallandco.ca": "Kendall & Co Interior Design & Decor",
    "admin@mapledrapery.com": "Maple Drapery and Carpet (1988 Ltd.)",
    "joy.pictureperfect@mail.com": "Picture Perfect Window Coverings",
    "graham@promarkwindowfilm.com": "Promark Window Film & Blinds",
    "cheryl@stevansinc.com": "Stevans Sales",
    "kevin@condokandy.com": "Suite Shades by KANDY (KANDY Operations Inc.)",
    "Sales@OntarioWallbeds.com": "London Window Treatment Inc.",
    "raphael.a@kendallandco.ca": "Kendall & Co Interior Design & Decor",
    "van@promarkwindowfilm.com": "Promark Window Film & Blinds",
    "amanda@stevansinc.com": "Stevans Sales",
    "retail@mysunglow.com": "Sun Glow Window Covering Products of Canada Ltd.",
    "sales@mysunglow.com": "Sun Glow Window Covering Products of Canada Ltd.",
    "bob.clemens@sympatico.ca": "AM 398775 - Artistic Interiors",
    "egeerlinks@gmail.com": "HH-Home Building Centre Lindsay (Store # 1759-4)",
    "sarah.wilhelm@homehardware.ca": "HH-Home Building Centre Lindsay (Store # 1759-4)",
    "elisa@hbclindsay.com": "HH-Home Building Centre Lindsay (Store # 1759-4)",
    "ellasworkroom@gmail.com": "Ella's Drapery & Blinds",
    "labadieblinds@rogers.com": "Labadie Blinds",
    "greg.shanks.allans@gmail.com": "HH-Allan's Home Hardware (Store # 1410-6)",
    "bradfordhh@rogers.com": "HH-Bradford Home Hardware (Store # 1375-2)",
    "matthew.myers@homehardware.ca": "HH-Carter's Home Hardware (Store # 1356-6)",
    "mark.begg@homehardware.ca": "HH-Crysler Home Hardware (Store # 1832-0)",
    "pierre.seguin@homehardware.ca": "HH-Crysler Home Hardware (Store # 1832-0)",

    "krista.mcbay@homehardware.ca": "HH-Elmira Home Hardware (Store # 1028-3)",
    "marnold@granderie.net": "HH-Granderie Limited (Store # 1105-1)",
    "hbclandy@cogeco.net": "HH-Home Bldg. Centre Leamington (Store # 1709-9)",
    "pat.ihh@ns.aliantzinc.ca": "HH-Ingonish Home Hardware (Store # 3235-8)",
    "home1422@hotmail.com": "HH-Mannila's Hardware Limited (Store # 1422-9)",
    "mike.morrow@homehardware.ca": "HH-Powassan Home Hardware (Store # 1679-2)",
    "richard@homevm.ca": "HH-Quincaillerie Ville-Marie Inc. (Store # 1332-0)",
    "lonnie.doherty@homehardware.ca": "HH-Walden Home Hardware (Store # 1562-3)",
    "dgreig@langdonmills.com": "HH-Westgate Village Home Hardware (Store # 1556-8)",
    "kelly.wilson@homehardware.ca": "HH-Wilson's Alcona Home Hardware (Store # 1603-5)",
    "luanne@mcnamarareynolds.com": "AM 10011624 - McNamara & Reynolds",
    "doverpaint@gmail.com": "Dover Paint & Paper",
    "mvlrconsulting@gmail.com": "MVLR Design, Sales & Consulting",
    "peterlavalle@evanslumber.ca": "HH-Evans Home Building Centre (Store # 1748-9)",
    "karenadurnell@gotchacovered.com": "Gotcha Covered Oakville (Decor By Karena Inc)",
    "helpmer@rogers.com": "Help Me Rhonda's Interiors",
    "contact@helmerhondas.ca": "Help Me Rhonda’s Interiors",
    "townandcountry@nexicom.net": "AM 397759 - Town & Country Decorating Centre Inc.",
    "rhonda@rtdressings.com": "RT Dressing Inc",
    "h.mirzaei@smartplace.ca": "Canada Smart Place",
    "denise.greig@homehardware.ca": "HH-Westgate Village Home Hardware (Store # 1556-8)",
    "sarah.brun@homehardware.ca": "HH-Westgate Village Home Hardware (Store # 1556-8)",
    # Adding From Basil
    "expressiondecor@hotmail.com": "AM 210104 - Expression Decor Inc",
    "peter.wickens@homehardware.ca": "HH-Barry's Home Hardware (Store # 1581-1)",
    "barryhh@homehardware.ca": "HH-Barry's Home Hardware (Store # 1581-1)",
    "louise@sunshade.ca": "Sunshade Blinds & Drapes",
    # End
    "wendyhadad@me.com": "Boutique Blinds & Home Inc./Ottawa Shutter Centre",
    "mypaintanddecor@hotmail.com": "AM 315311 - My Paint & Decor",
    "millshome@bmts.com": "HH-Mills Home Hardware (Store # 1553-4)",
    "endlessideas@rogers.com": "Endless Ideas Interiors Inc.",
    "maura@endlessideas.ca": "Endless Ideas Interiors Inc.",
    "Ehussey530@gmail.com": "Evalasting Window Coverings",
    "pappanodesign@sympatico.ca": "Pappano Design",
    "meritdecorating@rogers.com": "Merit Decor Centre",
    "pldevries@rogers.com": "Pamela de Vries Designs",
    "Millshome@bmts.com": "HH-Mills Home Hardware (Store # 1553-4)",
    "chris@proshade.ca": "ProShade Inc",
    "karen@mainandcompanyinteriors.com": "Main & Company Interiors Inc.",
    "Willi@CoversCanada.ca": "Covers Canada Inc.",
    "rosey.zehr@homehardware.ca": "HH-Wellesley Home Centre (Store # 1607-7)",
    "paola@luisasdraperies.com": "Luisa's Draperies + Interiors Ltd.",
    "Ehussey530@gmail.com": "Evalasting Window Coverings",
    "betty.harper@homehardware.ca": "HH-Home Hardware - St. Jacobs (Store # 1578-8)",
    "braddenshome@gmail.com": "Bradden's Home Improvements",
    "design@blindinfusion.com": "Blind Infusion",
    "danhladil@gmail.com": "HH-Smith & Hladil Home Hardware (Store # 1769-1)",
    "judy.pictureperfect@gmail.com": "Picture Perfect Window Coverings",
    "Rocco.fenuta@hotmail.com": "Sunscape Window Coverings",
    "lena@hilltopinteriors.com": "Hilltop Interiors",
    "andrew@proshade.ca": "ProShade Inc",
    "rkaemannila@gmail.com": "HH-Mannila's Hardware Limited (Store # 1422-9)",
    "jasmina@shadesofhome.ca": "Shades of Home",
    "sgaudet@drapeplace.ca": "Gaudet Fabric Limited",
    "smileysandra63@gmail.com": "Drapes & Blinds by Finishing Touches",
    "hbarichello@gmail.com": "Shades of Home",
    "zyb@commercialdraperies.ca": "Commercial Draperies and Blinds Ltd",
    "lisa@stewartsdecorating.com": "Stewart's Decorating",
    "jone.wright@sympatico.ca": "JW Designs /Lemon Lime Design",
    "bonnie.claveau@homehardware.ca": "HH-Hornepayne Home Hardware (Store # 1617-4)",
    "marcelo@smileflooring.ca": "Smile Carpets & Blinds",
    "valance@kent.net": "Affordable Elegance",
    "maplepaints@gmail.com": "AM 302176 - Maple Paints & Wallpaper",
    "info@peacockandowl.com": "Peacock & Owl (11555405 Canada Inc.)",
    "keneppenberger@focusondecorating.ca": "AM 397753 - Focus On Decorating",
    "info@nulookblinds.com": "Nulook Blinds & Draperies",
    "gillian@gilliangillies.com": "Gillian Gillies Interiors",
    "marieiannace@gmail.com": "Shades of Home",
    "tara@sunnexblinds.com": "Store Import (Store Import S.E.N.C.)",
    "info@sunnexblinds.com": "Store Import (Store Import S.E.N.C.)",
    "sales@solarshades.ca": "Blinds & Designs",
    "andrea@ahhome.ca": "Andrea Hylton Home (Feather Thy Nest Inc)",
    "deborah@impressiveinteriors.ca": "Impressive Interiors",
    "Steve.poxon@yahoo.ca": "Shades of Home",
    "hamed@smartav.com": "Smart AV Inc",
    "rgarrecht@a-phaseelectric.com": "A-Phase Electrical Contracting Services Ltd.",
    "rgarrecht@a-phaseelect.com": "A-Phase Electrical Contracting Services Ltd.",
    "cathy@abrighterworld.ca": "A Brighter World",
    "zoe@carriagelanedesigns.com": "Carriage Lane Design Build Inc.",
    "dgrenier@dms-noramtex.com": "D M S",
    "cinziadesign@rogers.com": "Cinzia Design",
    "betterblinds1@live.com": "Better Blinds And Drapery",
    "lisal@coverscanada.ca": "Covers Canada Inc.",
    "ron.shunter@homehardware.ca": "HH-POPS Home Hardware Building C. (Store # 5478-2)",
    "cathleenv@gotchacovered.com": "Gotcha Covered Ottawa",
    "Bonnie.Claveau@homehardware.ca": "HH-Hornepayne Home Hardware (Store # 1617-4)",
    "donna@blisshomeinnovations.com": "Bliss Home Innovations",
    "accountsfurnanddecor@haydesign.ca": "Hay Design Incorporated",
    # "shannon@ellasdrapery.ca": "AM 8984490 - Ella's Drapery & Blinds",
    "tamaracluff@gotchacovered.com": "Gotcha Covered of Edmonton and St. Albert",
    "tom@tnsblinds.ca": "TNS Custom Blinds Inc.",
    "adminfurnanddecor@haydesign.ca": "Hay Design Incorporated",
    "decoratingelements1500@gmail.com": "AM 396730 - Decorating Elements",
    "liana@mapledrapery.com": "Maple Drapery and Carpet (1988 Ltd.)",
    "patricia@mapledrapery.com": "Maple Drapery and Carpet (1988 Ltd.)",
    "dean@centraltarp.com": "Central Tarp Ltd.",
    "chall@west-port.com": "Westport Manufacturing Co. Ltd.",
    "kated@endlessideas.ca": "Endless Ideas Interiors Inc.",
    "thedraperywoman@gmail.com": "The Drapery Woman Ltd.",
    "Lloydminster@endoftheroll.com": "End Of The Roll (41416 Lloydminster)",
    "stuart@stormdesigninc.ca": "Storm Design Inc.",
    "myshadeosun@gmail.com": "Shade-O-Sun",
    "felicia@sunshade.ca": "Sunshade Blinds & Drapes",
    "amanda@elitedraperies.ca": "Elite Draperies & Home Decorating",
    "info@pineappledesign.ca": "Pineapple Design",
    "peggy@coverscanada.ca": "Covers Canada Inc.",
    "totalwindows@sympatico.ca": "Total Windows",
    "mashar@gotchacovered.com": "Gotcha Covered - Tomka Consultec & Design Inc.",
    "keith.duggan@homehardware.ca": "HH-Sharbot Lake Home Building Ctr (Store # 1581-9)",
    "shaurya.shah@samyaktrade.com": "Kazumi Window Coverings (Samyak Inc.)",
    "info@lincolndesignhouse.ca": "Lincoln Design House",
    "hamed@smartav.ca": "Smart AV Inc",
    "josette@coverscanada.ca": "Covers Canada Inc.",
    "jonw@jwautomation.ca": "Jon Wilson Automation",
    "charlenesunshades@gmail.com": "Sunshades Window Fashions Decorator",
    "OCS - Client": "Off Cut Shades",
    "ridgetown@homehardware.ca": "HH-Carter's Home Hardware (Store # 1356-6)",
    "pmacginty@hurontel.on.ca": "Blissful Blinds",
    "covers5@coverscanada.ca": "Covers Canada Inc.",
    "covers2@coverscanada.ca": "Covers Canada Inc.",
    "info@stridedesign.ca": "Stride Design Collective Inc.",
    "hello@goodhaus.ca": "Goodhaus Blinds & Design",
    "info@saskblindfactory.com": "Distinctive Draperies(The Blind Factory)",
    "lisa@stradwicksnorthbay.com": "Stradwicks Carpet One North Bay",
    "stcatherines@endoftheroll.com": "THD 7023 St Catharines",
    "len@pollockshomehardware.ca": "HH-Pollocks Home Hardware (Store # 1437-6)",
    "kevin@ctlfreak.com": "Control Freak Consulting",

    #
    "amugabe@venacorp.com": "Veena Solutions",
    "Lisa1991@bell.net": "Lisa Pinkney",
    "smm5762@gmail.com": "Shannon McLaughlin",
    "cvergut@rogers.com": "Cheryl Vergut",
    "mcg101@icloud.com": "John MacKenzie",
    "info@skyblinds.ca": "Sky Blinds Inc",
    "ferenah@sympatico.ca": "Ferenah Karimullah",
    "lorint.uxbridge@gmail.com": "Lorelei Interiors",

    "lavieencouleur_decor@hotmail.com": "La Vie En Couleur & Decor",
    "colourconceptsbychristine@gmail.com": "Colour Concepts By Christine",
    "jbes@rogers.com": "BesOxford Upholstery",
    "jessica@hemmecustom.com": "Hemme Custom Inc",
    "mandy@hemmecustom.com": "Hemme Custom Inc",
    "nuccitelliv@gmail.com": "Dome Decor",
    "shannon@embellish.ca": "AM 8984490 - Embellish",
    "johanna@drapetek.com": "DrapeTek Hospitality",

    "dave@boraxwindowfashions.com": "Borax Window Fashions Calgary",
    "pennywallerinteriors@gmail.com": "Waller Interiors",
    "allanr@quintehomesolutions.ca": "Quinte Homes Solutions",
    "heather@heerspaint.com": "Heers Paint",
    "admin@kathiejordandesign.com": "Kathie Jordan Design",

    "susancarolblack@gmail.com": "Susan Black",
    "s_gavric@hotmail.com": "Slavisa Gavric",
    "hi@littleredcoffee.ca": "Little Red Coffee",
    "steve@elitetechnology.ca": "Elite Technology Systems",
    "jmarmer@plazacorp.com": "Plazacorp",
    "kumail@remtulla.com": "Everest Whole Health Pharmacy",
    "depaz.alex@gmail.com": "Alex De Paz",
    "rob.fong@gmail.com": "Rob Fong",
    "handymacd@gmail.com": "Dustin MacDougal",
    "margaretparry.ca@gmail.com": "Margaret  Parry",
    "ferrellkim50@gmail.com": "Kim Ferrell",
    "currya14@gmail.com": "Alison Curry",
    "ricotovi@surenet-it.com": "Ricardo Coto Oviedo",
    "info@ashinteriors.ca": "Ash Interiors",
    "paula.m.spicer@gmail.com": "Paula Spicer",
    "john.a.mckee@icloud.com": "John Mckee",
    "peter@peterbride.ca": "Peter Bride",
    "": "Denise Jiang",
    "John.Orenchuk@toronto.ca": "John P. Orenchuk",
    "masooma@interiorpersona.com": "Interior Persona",
    "": "Blindware PLY LTD",
    "dave.lauzon@broccolini.com": "Broccolini Construction (Toronto) Inc.",
    "info@drapesbyus.com": "Custom Drapery & Blinds By Us(13939031 Canada Inc)",
    "englandanne1@gmail.com": "Anne England",


}

# 50/35

accountsCode = {
    "finedeco@rogers.com": "10254C",
    "StuartStorm@gotchacovered.com": "11562C",
    "Gotchacoveredtorontocentral@gmail.com": "11562C",
    "Lindsay@patti-lynn.com": "10228C",
    "john@mapledrapery.com": "10603C",
    "joannabaker81@gmail.com": "10342C",
    "william@eurofab.ca": "10260C",
    "kellie@drapeology.com": "11759C",
    "sebastien@mysunglow.com": "10376C",
    "Al@200Vic.com": "11629C",
    "admin@2codesign.ca": "11331C",
    "kenluu618@yahoo.com": "10829C",
    "amit@coloursandmore.com": "11683C",
    "thomsens@rogers.com": "11686C",
    "mikem@paintdepot.com": "11753C",
    "artisticinteriors@hotmail.com": "11665C",
    "karen@ashtonsblinds.com": "10335C",
    "Info@auropol.ca": "11566C",
    "sherree@avenuelighting.ca": "10149C",
    "avenueofstyles@gmail.com": "11751C",
    "stefanie@blindsareus.ca": "10187C",
    "Showroom@blindsareus.ca": "10187C",

    "blindspot@fibreop.ca": "11215C",
    "beverley@cocooninteriors.ca": "11185C",
    "yolanda@colouroasis.ca": "11722C",
    "petra@cvshading.com": "10279C",
    "anita@cvshading.com": "10279C",

    "dani@gambitventures.ca": "11277C",
    "coverups@outlook.com": "10275C",
    "lilyandvince@dekoblinds.ca": "11559C",
    "james@devineblinds.net": "11310C",
    "charlenebertini@gmail.com": "11659C",
    "don@drapeology.com": "11759C",
    "maria@drapesandmore.ca": "10264C",
    "barbara@evershades.ca": "11600C",
    "info@faabhomefashions.com": "11531C",
    "lbildfell@flooringandhome.com": "11760C",
    "georgiaprendergast@gotchacovered.com": "11701C",
    "peterbuchsbaum@gotchacovered.com": "11657C",
    "clairwoodland@gotchacovered.com": "11653C",
    "croteau@gotchacovered.com": "11561C",
    "mikecyr@gotchacovered.com": "11560C",
    "bakers@gotchacovered.com": "11652C",
    "carolannhorvat@gotchacovered.com": "11537C",
    "insideideas@bellnet.ca": "10151C",
    "Jalynwirth@gmail.com": "10315C",
    "kathryn@kathrynastoninteriors.com": "11010C",
    "kazumicovering@gmail.com": "11749C",
    "kevin@kendallandco.ca": "10586C",
    "design@kingstonpaint.com": "10561C",
    "harvey@lrnerinteriors.com": "10238C",
    "info@lincolndesignhouse.ca": "11716C",
    "purchasing@mnidonline.com": "11058C",
    "rethier@gmail.com": "10815C",
    "lindsay@patti-lynn.com": "10228C",
    "tscustomdrapery@hotmail.com": "10805C",
    "info@promarkwindowfilm.com": "10132C",
    "1dilu1@gmail.com": "11334C",
    "amanda@rbfurnitureshop.com": "11762C",
    "rmcavoy_design@yahoo.ca": "11233C",
    "douglaswentzel@bellnet.ca": "10222C",
    "rosewell.interiors@gmail.com": "11021C",
    "dan@shuttercraft.ca": "11408C",
    "bren@swi.design": "10146C",
    "annfitch@stevansinc.com": "10126C",
    "doug@condokandy.com": "11747C",
    "sunsetblinds@hurontel.on.ca": "10340C",
    "taipan2004@rogers.com": "10210C",
    "karen_gordon@rogers.com": "10106C",
    "blinds@thedecoratingcentre.ca": "10631C",
    "wardsdraperies@rogers.com": "10203C",
    "John@OntarioWallBeds.com": "11538C",
    "kelly@coloursandmore.com": "11683C",
    "alanna@paintdepot.com": "11753C",
    "larissa@avenuelighting.ca": "10149C",
    "ashley@thebauhaus.ca": "10187C",
    "chris@colouroasis.ca": "11722C",
    "sales@cvshading.com": "10279C",
    "jordan@condoblinds.com": "11277C",
    "admin@drapesandmore.ca": "10264C",
    "psierra@flooringandhome.com": "11760C",
    "jjwirth@telus.net": "10315C",
    "kendall@kendallandco.ca": "10586C",
    "lukas@mapledrapery.com": "10603C",
    "nbblinds.sally@gmail.com": "10815C",
    "PATTI-LYNN@PATTI-LYNN.COM": "10228C",
    "judy.pictureperfect@gmail.com": "10805C",
    "bschaefer@promarkwindowfilm.com": "10132C",
    "kristilee@rbfurnitureshop.com": "11762C",
    "westwoodwindowfashions@sympatico.ca": "10343C",
    "jennifer@swi.design": "10146C",
    "becky@stevansinc.com": "10126C",
    "kelly@condokandy.com": "11747C",
    "yvonnebc1@rogers.com": "10210C",
    "drapery@thedecoratingcentre.ca": "10631C",
    "Amy@OntarioWallBeds.com": "11538C",
    "info@coloursandmore.com": "11683C",
    "sarah@paintdepot.com": "11753C",
    "kayla@avenuelighting.ca": "10149C",
    "jody@colouroasis.ca": "11722C",
    "will@kendallandco.ca": "10586C",
    "admin@mapledrapery.com": "10603C",
    "joy.pictureperfect@mail.com": "10805C",
    "graham@promarkwindowfilm.com": "10132C",
    "cheryl@stevansinc.com": "10126C",
    "kevin@condokandy.com": "11747C",
    "Sales@OntarioWallbeds.com": "11538C",
    "raphael.a@kendallandco.ca": "10586C",
    "van@promarkwindowfilm.com": "10132C",
    "amanda@stevansinc.com": "10126C",
    "retail@mysunglow.com": "10376C",
    "sales@mysunglow.com": "10376C",
    "bob.clemens@sympatico.ca": "11665C",
    "egeerlinks@gmail.com": "11800C",
    "sarah.wilhelm@homehardware.ca": "11800C",
    "elisa@hbclindsay.com": "11800C",
    "ellasworkroom@gmail.com": "10261C",
    "labadieblinds@rogers.com": "10142C",
    "greg.shanks.allans@gmail.com": "None",
    "bradfordhh@rogers.com": "None",
    "matthew.myers@homehardware.ca": "11792C",
    "mark.begg@homehardware.ca": "11803C",
    "pierre.seguin@homehardware.ca": "11803C",

    "krista.mcbay@homehardware.ca": "11806C",
    "marnold@granderie.net": "None",
    "hbclandy@cogeco.net": "11811C",
    "pat.ihh@ns.aliantzinc.ca": "11793C",
    "home1422@hotmail.com": "11814C",
    "mike.morrow@homehardware.ca": "None",
    "richard@homevm.ca": "None",
    "lonnie.doherty@homehardware.ca": "None",
    "dgreig@langdonmills.com": "None",
    "kelly.wilson@homehardware.ca": "None",
    "luanne@mcnamarareynolds.com": "11787C",
    "doverpaint@gmail.com": "10952C",
    "mvlrconsulting@gmail.com": "11718C",
    "peterlavalle@evanslumber.ca": "11839C",
    "karenadurnell@gotchacovered.com": "11558C",
    "helpmer@rogers.com": "10249C",
    "contact@helmerhondas.ca": "10249C",
    "townandcountry@nexicom.net": "11717C",
    "rhonda@rtdressings.com": "11287C",
    "h.mirzaei@smartplace.ca": "11441C",
    "denise.greig@homehardware.ca": "11797C",
    "sarah.brun@homehardware.ca": "11797C",
    # Adding From Basil
    "expressiondecor@hotmail.com": "11835C",
    "peter.wickens@homehardware.ca": "11845C",
    "barryhh@homehardware.ca": "11845C",
    "louise@sunshade.ca": "10214C",
    # End
    "wendyhadad@me.com": "11284C",
    "mypaintanddecor@hotmail.com": "10953C",
    "millshome@bmts.com": "11820C",
    "endlessideas@rogers.com": "11001C",
    "maura@endlessideas.ca": "11001C",
    "Ehussey530@gmail.com": "11626C",
    "pappanodesign@sympatico.ca": "11763C",
    "meritdecorating@rogers.com": "11188C",
    "pldevries@rogers.com": "11037C",
    "Millshome@bmts.com": "11820C",
    "chris@proshade.ca": "11314C",
    "karen@mainandcompanyinteriors.com": "10154C",
    "Willi@CoversCanada.ca": "10177C",
    "rosey.zehr@homehardware.ca": "11836C",
    "paola@luisasdraperies.com": "11313C",
    "Ehussey530@gmail.com": "11626C",
    "betty.harper@homehardware.ca": "11875C",
    "braddenshome@gmail.com": "11782C",
    "design@blindinfusion.com": "11246C",
    "danhladil@gmail.com": "11876C",
    "judy.pictureperfect@gmail.com": "10805C",
    "Rocco.fenuta@hotmail.com": "11431C",
    "lena@hilltopinteriors.com": "10248C",
    "andrew@proshade.ca": "11314C",
    "rkaemannila@gmail.com": "11814C",
    "jasmina@shadesofhome.ca": "11235C",
    "sgaudet@drapeplace.ca": "10252C",
    "smileysandra63@gmail.com": "10954C",
    "hbarichello@gmail.com": "11235C",
    "zyb@commercialdraperies.ca": "11898C",
    "lisa@stewartsdecorating.com": "10028C",
    "jone.wright@sympatico.ca": "10097C",
    "bonnie.claveau@homehardware.ca": "11825C",
    "marcelo@smileflooring.ca": "11270C",
    "valance@kent.net": "10198C",
    "maplepaints@gmail.com": "11871C",
    "info@peacockandowl.com": "11906C",
    "keneppenberger@focusondecorating.ca": "11697C",
    "info@nulookblinds.com": "10095C",
    "gillian@gilliangillies.com": "10624C",
    "marieiannace@gmail.com": "11235C",
    "info@sunnexblinds.com": "11684C",
    "tara@sunnexblinds.com": "11684C",
    "sales@solarshades.ca": "11497C",
    "andrea@ahhome.ca": "11916C",
    "deborah@impressiveinteriors.ca": "10022C",
    "hamed@smartav.com": "11621C",
    "Steve.poxon@yahoo.ca": "11235C",
    "rgarrecht@a-phaseelectric.com": "11724C",
    "rgarrecht@a-phaseelect.com": "11724C",
    "cathy@abrighterworld.ca": "10179C",
    "zoe@carriagelanedesigns.com": "11659C",
    "dgrenier@dms-noramtex.com": "10045C",
    "cinziadesign@rogers.com": "11344C",
    "betterblinds1@live.com": "10430C",
    "lisal@coverscanada.ca": "10177C",
    "ron.shunter@homehardware.ca": "11883C",
    "cathleenv@gotchacovered.com": "11556C",
    "Bonnie.Claveau@homehardware.ca": "11825C",
    "donna@blisshomeinnovations.com": "11335C",
    "accountsfurnanddecor@haydesign.ca": "11266C",
    # "shannon@ellasdrapery.ca": "11868C",
    "tamaracluff@gotchacovered.com": "11908C",
    "tom@tnsblinds.ca": "11440C",
    "adminfurnanddecor@haydesign.ca": "11266C",
    "decoratingelements1500@gmail.com": "11667C",
    "liana@mapledrapery.com": "10603C",
    "patricia@mapledrapery.com": "10603C",
    "dean@centraltarp.com": "11364C",
    "chall@west-port.com": "10343C",
    "kated@endlessideas.ca": "11001C",
    "thedraperywoman@gmail.com": "11649C",
    "Lloydminster@endoftheroll.com": "11892C",
    "stuart@stormdesigninc.ca": "11562C",
    "myshadeosun@gmail.com": "11132C",
    "felicia@sunshade.ca": "10214C",
    "amanda@elitedraperies.ca": "10555C",
    "info@pineappledesign.ca": "10641C",
    "peggy@coverscanada.ca": "10177C",
    "totalwindows@sympatico.ca": "11943C",
    "mashar@gotchacovered.com": "11929C",
    "keith.duggan@homehardware.ca": "11827C",
    "shaurya.shah@samyaktrade.com": "11749C",
    "info@lincolndesignhouse.ca": "11716C",
    "hamed@smartav.ca": "11621C",
    "josette@coverscanada.ca": "10177C",
    "jonw@jwautomation.ca": "11426C",
    "charlenesunshades@gmail.com": "11147C",
    "OCS - Client": "11745C",
    "ridgetown@homehardware.ca": "11792C",
    "pmacginty@hurontel.on.ca": "11761C",
    "covers5@coverscanada.ca": "10177C",
    "covers2@coverscanada.ca": "10177C",
    "info@stridedesign.ca": "12188C",
    "hello@goodhaus.ca": "12154C",
    "info@saskblindfactory.com": "10032C",
    "lisa@stradwicksnorthbay.com": "11217C",

    "stcatherines@endoftheroll.com": "12209C",
    "len@pollockshomehardware.ca": "11886C",
    "kevin@ctlfreak.com": "12160C",

    #
    "lavieencouleur_decor@hotmail.com": "11670C",

    "colourconceptsbychristine@gmail.com": "10707C",
    "jbes@rogers.com": "10191C",
    "jessica@hemmecustom.com": "12220C",
    "mandy@hemmecustom.com": "12220C",
    "nuccitelliv@gmail.com": "12152C",
    "shannon@embellish.ca": "11868C",
    "amugabe@venacorp.com": "12286C",
    "Lisa1991@bell.net": "12287C",
    "smm5762@gmail.com": "12288C",
    "cvergut@rogers.com": "12289C",
    "mcg101@icloud.com": "12290C",
    "info@skyblinds.ca": "12291C",
    "ferenah@sympatico.ca": "12292C",
    "lorint.uxbridge@gmail.com": "12293C",





    "dave@boraxwindowfashions.com": "11055C",
    "pennywallerinteriors@gmail.com": "11768C",
    "allanr@quintehomesolutions.ca": "12214C",
    "heather@heerspaint.com": "12238C",
    "admin@kathiejordandesign.com": "12224C",

    "johanna@drapetek.com": "12285C",
    "susancarolblack@gmail.com": "12295C",
    "s_gavric@hotmail.com": "12296C",
    "hi@littleredcoffee.ca": "12297C",
    "steve@elitetechnology.ca": "12302C",
    "jmarmer@plazacorp.com": "12303C",
    "kumail@remtulla.com": "12304C",
    "depaz.alex@gmail.com": "12305C",
    "rob.fong@gmail.com": "12306C",
    "handymacd@gmail.com": "12307C",
    "margaretparry.ca@gmail.com": "12308C",
    "ferrellkim50@gmail.com": "12309C",
    "currya14@gmail.com": "12310C",
    "ricotovi@surenet-it.com": "12311C",
    "info@ashinteriors.ca": "12312C",
    "paula.m.spicer@gmail.com": "12313C",
    "john.a.mckee@icloud.com": "12314C",
    "peter@peterbride.ca": "12315C",
    "": "12316C",
    "John.Orenchuk@toronto.ca": "12317C",
    "masooma@interiorpersona.com": "12318C",
    "": "12319C",
    "dave.lauzon@broccolini.com": "12320C",
    "info@drapesbyus.com": "12321C",
    "englandanne1@gmail.com": "12322C",

    # "": "", "": "", "": "",

}
